# Generated by Django 5.1.4 on 2025-01-05 01:39

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prediccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edad', models.CharField(blank=True, max_length=255, null=True)),
                ('sexo_biologico', models.CharField(blank=True, max_length=255, null=True)),
                ('escolaridad', models.TextField(blank=True, null=True)),
                ('estrato_socioeconomico', models.TextField(blank=True, null=True)),
                ('prediccion', models.CharField(max_length=50)),
                ('probabilidad_clase_1', models.FloatField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrediccionUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edad', models.IntegerField()),
                ('sexo_biologico', models.CharField(max_length=10)),
                ('escolaridad', models.CharField(max_length=50)),
                ('estrato_socioeconomico', models.IntegerField()),
                ('estado_civil', models.CharField(max_length=20)),
                ('area_urbana_rural', models.CharField(max_length=10)),
                ('comorbilidades', models.TextField()),
                ('prediccion', models.IntegerField()),
                ('probabilidad_clase_1', models.FloatField()),
                ('fecha', models.DateTimeField(default=timezone.now)),
                ('es_entrenamiento', models.BooleanField(default=False)),
            ],
        ),
    ]