# Generated by Django 5.1.4 on 2025-01-06 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo_random', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prediccion',
            name='es_entrenamiento',
            field=models.BooleanField(default=False),
        ),
    ]
